INSERT INTO CLIENT ("CREATED_AT", "EMAIL", "NAME", "PHONE_NUMBER", "UPDATED_AT", "VAT_NUMBER") VALUES (CURRENT_TIMESTAMP, 'email@gmail.com', 'name1', '912345678', CURRENT_TIMESTAMP, '123456789');
INSERT INTO CLIENT ("CREATED_AT", "EMAIL", "NAME", "PHONE_NUMBER", "UPDATED_AT", "VAT_NUMBER") VALUES (CURRENT_TIMESTAMP, 'email@gmail.com', 'name2', '912327578', CURRENT_TIMESTAMP, '123658789');

INSERT INTO ADDRESS ("APARTMENT_INFORMATION", "CITY", "CREATED_AT", "NICKNAME", "STREET_NAME", "STREET_NUMBER", "UPDATED_AT", "ZIP_CODE", "CLIENT_ID") VALUES (null, 'city', CURRENT_TIMESTAMP, 'house', 'str1', 10, CURRENT_TIMESTAMP, '1234-123', 1);
INSERT INTO ADDRESS ("APARTMENT_INFORMATION", "CITY", "CREATED_AT", "NICKNAME", "STREET_NAME", "STREET_NUMBER", "UPDATED_AT", "ZIP_CODE", "CLIENT_ID") VALUES (null, 'city', CURRENT_TIMESTAMP, 'house', 'str27', 98, CURRENT_TIMESTAMP, '1234-578', 2);

INSERT INTO CATEGORY ("CREATED_AT", "NAME", "UPDATED_AT") VALUES (CURRENT_TIMESTAMP, 'cat1', CURRENT_TIMESTAMP);

INSERT INTO PRODUCT ("CREATED_AT", "NAME", "PRICE", "STOCK", "UPDATED_AT", "CATEGORY_ID") VALUES (CURRENT_TIMESTAMP, 'prod1', 20.0, 10, CURRENT_TIMESTAMP, 1);